### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#783]
Pulled and tried to build the latest in development branch by running mvn install -Dtycho.localArtifacts=ignore

I'm getting this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install (default-install) on project com.ge.research.sadl.product: NoFileAssignedException: The packaging plugin for this project did not assign a main file to the project but it has attachments. Change packaging to 'pom'. -> [Help 1]

**Comment by tuxji** [comment]
Fixed in commit [0fafd52c08c3b9bf5e9c7dea9d936ce8de64c46b](https://github.com/SemanticApplicationDesignLanguage/sadl/commit/0fafd52c08c3b9bf5e9c7dea9d936ce8de64c46b).

**Comment by agabaldon** [comment]
Still not working for me. Getting:

[INFO] Computing target platform for MavenProject: com.ge.research.sadl:com.ge.research.sadl.product:3.5.0-SNAPSHOT @ /Users/alfredo/Documents/git/sadl/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.product/pom.xml
[INFO] Resolving dependencies of MavenProject: com.ge.research.sadl:com.ge.research.sadl.product:3.5.0-SNAPSHOT @ /Users/alfredo/Documents/git/sadl/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.product/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: sadl.product 3.5.0.qualifier
[ERROR]   Missing requirement: sadl.product 3.5.0.qualifier requires 'org.eclipse.equinox.p2.iu; org.eclipse.sdk.feature.group 0.0.0' but it could not be found
[ERROR] 
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: com.ge.research.sadl:com.ge.research.sadl.product:3.5.0-SNAPSHOT @ /Users/alfredo/Documents/git/sadl/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.product/pom.xml: See log for details -> [Help 1]
